### ISSUE TITLE
No %python2_clone and %python3_clone

### ISSUE THREAD

**Issue by toddrme2178** [openSUSE/python-rpm-macros#10]
For most macros, there is a %python_foo version and a corresponding `%python2_foo` and `%python3_foo` version. The only exception I have noticed is `%python_clone`, which does not have a corresponding `%python2_clone` or `%python3_clone`. This would be useful in packages where the python2 and python3 versions have to be packaged separately (generally because the latest version is python3-only), but where we still have conflicting files between the two packages.

**Comment by mcepl** [comment]
This is completely obsolete.
