### ISSUE TITLE
How to set environment variables for specific flavors?

### ISSUE THREAD

**Issue by miq** [openSUSE/python-rpm-macros#105]
I want to package a project that links against boost_python and uses the environment variable BOOST_PYTHON_LIB to determine the shared library to link against.

I tried using something like

%build
export CFLAGS="%{optflags}"
%if "%{python_flavor}" == "python2"
  export BOOST_PYTHON_LIB="boost_python-py2_7"
%else
  export BOOST_PYTHON_LIB="boost_python-py3"
%endif
%python_build

to build the package but the python3 version is linked against boost_python-py2_7. I guess that the if is only evaluated once and not in the %python_build loop.

How can I achieve a correct evaluation and exporting of environment variables for all flavors?

**Comment by bnavigator** [comment]
Hello,

1. libboost_python is only for python3, which maps to python38. There is no python36 variant right now, so you have to limit your package to python3 or python38 as well. -- See https://build.opensuse.org/request/show/869604?notification_id=25079662#comments-list
2. `%python_flavor` does not work in plain `%build`. See the README entry for the macro. The ` %build` section is not run for each flavor but only once. The iteration happens inside `%python_build` only. `BOOST_PYTHON_LIB` is set once to whatever the conditional evaluated to (different default value for `%python_flavor` for different distros)
3. Do you really need to support Python2? If not, together with (1.), there only remains one flavor "python3", so you can omit all the singlspec magic together and just call %python3_build directly.

```spec
# pre-defined _without_python2 is in Tumbleweed Factory to skip python2 here
%bcond_without python2

%define pythons python3
%if %{with python2}
%define pythons python2 %pythons
%endif

[...]

%build
%if %{with python2}
export BOOST_PYTHON_LIB="boost_python-py2_7"
%python2_build
%endif
export BOOST_PYTHON_LIB="boost_python-py3"
%python3_build

# if you have custom calls for every python flavor, here is a hack using the _pseudo_ $python
# variable expansion of the python_expand macro:
python2_boostlib="boost_python-py2_7"
python3_boostlib="boost_python-py3"
%{python_expand #
export BOOST_PYTHON_LIB=${$python_boostlib}
./call_something_with_env_set
# you could even
%{$python_build}
}

%install
# if nothing extra has to be set, and pythons is well defined, you can still do
%python_install
```
