### ISSUE TITLE
Breaks builds (e.g., tex(symbol) is split)

### ISSUE THREAD

**Issue by mcepl** [openSUSE/python-rpm-macros#111]
See comments at https://build.opensuse.org/request/show/898077?notification_id=26614194

> Ouch - that breaks the deps of for example python-Sphinx-latex badly
>
> Please sort out in a devel area first
>
> e.g. tex(anyfontsize.sty) is split in two requires: 'tex' and '(anyfontsize.sty)'

**Comment by mcepl** [comment]
@bnavigator any thoughts, please?

**Comment by bnavigator** [comment]
Fixed by #112.

> Please sort out in a devel area first

https://build.opensuse.org/project/show/home:bnavigator:python-rpm-macros
