### ISSUE TITLE
Request to bring %python_compileall to python-rpm-macros

### ISSUE THREAD

**Issue by mcepl** [openSUSE/python-rpm-macros#114]
https://bugzilla.suse.com/show_bug.cgi?id=1189386

When implementing jsc#SLE-18648, we encounter a build problem that python-jupyter-core (required by graphical component) needs the mentioned macro to build. I tested the following commit should be enough for the requirement:

https://build.opensuse.org/package/view_file/home:yfjiang:home:yfjiang:gnome:stable41:infra/python-rpm-macros/db2f650ee3308f4bc0220ed43ed923773857b100.patch?expand=1

The bug is to request for a porting of the feature to sle-15-sp4:ga.

**Comment by bnavigator** [comment]
So updating the whole python-rpm-macros for SLE-15 SP4 (and lower, [boo#1187473](https://bugzilla.opensuse.org/show_bug.cgi?id=1187473) ) is out the window?

**Comment by bnavigator** [comment]
> python-jupyter-core (required by graphical component) needs the mentioned macro to build

You can always remove the macro or define it within the specfile itself, if updating python-rpm-macros is not an option:

```
%{?!python_compileall:%define python_compileall python3 -m compileall %{buildroot}%{python3_sitelib}; python3 -O -m compileall %{buildroot}%{python3_sitelib}}
```

**Comment by mcepl** [comment]
> So updating the whole python-rpm-macros for SLE-15 SP4 (and lower, [boo#1187473](https://bugzilla.opensuse.org/show_bug.cgi?id=1187473) ) is out the window?

No, it is not. It turns out, upgrading python-rpm-macros actually didn't make any problems in SLE-15, so we will certainly go with that.

This ticket was filed more for bookkeeping, but now I see that it is really just a duplicate of #60 and #63.

**Comment by mcepl** [comment]
@bnavigator Thinking about it: wouldn’t ``-f`` to ``compileall`` make sense? When building a package and explicitly calling this macro, we probably want just everything recompiled, don't we?

**Comment by bnavigator** [comment]
The present form of the macro deletes all pyc files before compiling anyway. So not much effect for `compileall -f`.

https://github.com/openSUSE/python-rpm-macros/blob/eccf3f222082e1c62dd06e3d48886bd53741c5e4/macros/010-common-defs#L172-L183

But we could probably add some form of `touch -m -r` to the macro as in https://build.opensuse.org/request/show/915453#n115 in order to prevent fdupes from creating reproducibility problems.

**Comment by mcepl** [comment]
> The present form of the macro deletes all pyc files before compiling anyway. So not much effect for `compileall -f`.
> 
> https://github.com/openSUSE/python-rpm-macros/blob/eccf3f222082e1c62dd06e3d48886bd53741c5e4/macros/010-common-defs#L172-L183
> 
> But we could probably add some form of `touch -m -r` to the macro as in https://build.opensuse.org/request/show/915453#n115 in order to prevent fdupes from creating reproducibility problems.

Not sure, what to point `touch -r` to. And feel free to suggest PR.

**Comment by mcepl** [comment]
OK, I have no idea, why I kept it alive.
