### ISSUE TITLE
export PYTHONPATH and  --import-mode=append required for successful python builds

### ISSUE THREAD

**Issue by skriesch** [openSUSE/python-rpm-macros#124]
I wanted to update the package python-zstandard to the latest version 0.17.0:
https://build.opensuse.org/package/show/home:AdaLovelace:branches:devel:languages:python/python-zstandard

It can not find successful integrated builds of the own module 'zstandard.backend_c' because PYTHONPATH is pointing to the the wrong directory, which is not used by the zstandard building process.
That is the reason that these new features with integrated modules can not be used.

That can be fixed with expanding PYTHONPATH with an export in the pytest section inside of the python-rpm-macros.

The second problem is that the tests can not run successfully without "--import-mode=append" after pytest in "osc chroot".
Do we want to have that as a default for all python packages or is there any solution how to expand our macros in the spec file with such options?

**Comment by bnavigator** [comment]
Hi,

> It can not find successful integrated builds of the own module 'zstandard.backend_c' because PYTHONPATH is pointing to the the wrong directory, which is not used by the zstandard building process. That is the reason that these new features with integrated modules can not be used.

Your example project of zstandard does not look right. Of course you are not allowed to set the `PYTHONPATH` to the 3.9 platlib for all flavors and with fixed version numbers in there.

> That can be fixed with expanding PYTHONPATH with an export in the pytest section inside of the python-rpm-macros.

PYTHONPATH *is* expanded inside the pytest section and pytest gets the correct PYTHONPATH for the flavor. 

``` shell
abuild@skylab:~> rpm -E '%pytest_arch'

last_flavor=`[ -f _current_flavor ] && cat _current_flavor || true` 
if [ -z "$last_flavor" ]; then last_flavor="tmp"; fi 
if [ "$last_flavor" != "python39" ]; then 
    if [ -d build ]; then mv build _build.$last_flavor; fi 
    if [ -d _build.python39 ]; then mv _build.python39 build; fi 
fi 
echo python39 > _current_flavor 
python_flavor=python39 

PYTHONPATH=${PYTHONPATH:+$PYTHONPATH:}/home/abuild/rpmbuild/BUILDROOT/%{NAME}-%{VERSION}-%{RELEASE}.x86_64/usr/lib64/python3.9/site-packages PYTHONDONTWRITEBYTECODE=1 pytest-3.9 --ignore=_build.python39 --ignore=_build.python310 --ignore=_build.python38 -v

last_flavor=`[ -f _current_flavor ] && cat _current_flavor || true` 
if [ -z "$last_flavor" ]; then last_flavor="tmp"; fi 
if [ "$last_flavor" != "python310" ]; then 
    if [ -d build ]; then mv build _build.$last_flavor; fi 
    if [ -d _build.python310 ]; then mv _build.python310 build; fi 
fi 
echo python310 > _current_flavor 
python_flavor=python310 

PYTHONPATH=${PYTHONPATH:+$PYTHONPATH:}/home/abuild/rpmbuild/BUILDROOT/%{NAME}-%{VERSION}-%{RELEASE}.x86_64/usr/lib64/python3.10/site-packages PYTHONDONTWRITEBYTECODE=1 pytest-3.10 --ignore=_build.python39 --ignore=_build.python310 --ignore=_build.python38 -v

last_flavor=`[ -f _current_flavor ] && cat _current_flavor || true` 
if [ -z "$last_flavor" ]; then last_flavor="tmp"; fi 
if [ "$last_flavor" != "python38" ]; then 
    if [ -d build ]; then mv build _build.$last_flavor; fi 
    if [ -d _build.python38 ]; then mv _build.python38 build; fi 
fi 
echo python38 > _current_flavor 
python_flavor=python38 

PYTHONPATH=${PYTHONPATH:+$PYTHONPATH:}/home/abuild/rpmbuild/BUILDROOT/%{NAME}-%{VERSION}-%{RELEASE}.x86_64/usr/lib64/python3.8/site-packages PYTHONDONTWRITEBYTECODE=1 pytest-3.8 --ignore=_build.python39 --ignore=_build.python310 --ignore=_build.python38 -v

```

You don't need to export it for pytest. The environment for any subprocess call is usually isolated, so exporting does not help there either.

> The second problem is that the tests can not run successfully without "--import-mode=append" after pytest in "osc chroot". Do we want to have that as a default for all python packages or is there any solution how to expand our macros in the spec file with such options?

Unfortunately there is no clear cut solution that generally works for all packages. Setting this flag explicitly does not work for other packages where we need another flag.

For platform dependend packages, where the test collection needs the tests but also the compiled modules, it is usually best to  make sure that there is no uncompiled source in the syspath. See cheroot for an example: https://build.opensuse.org/request/show/948103

**Comment by cboltz** [comment]
I helped Sarah with getting the updated python-zstandard package to build, and it looks like I did misread the build log, which has

```
[  264s] + PYTHONPATH=/home/abuild/rpmbuild/BUILDROOT/python-zstandard-0.17.0-32.1.x86_64/usr/lib64/python3.9/site-packages:/home/abuild/rpmbuild/BUILDROOT/python-zstandard-0.17.0-32.1.x86_64/usr/lib64/python3.9/site-packages
[  264s] + PYTHONDONTWRITEBYTECODE=1
[  264s] + pytest-3.9 --ignore=_build.python39 --ignore=_build.python310 --ignore=_build.python38 -v
```

From the build log it looked like PYTHONPATH gets set in a separate line/command, therefore I recommended exporting it. Looking at the `rpm --eval`ed macro, it's clear that it's set in the same command line (so pytest "sees" it), and exporting it is indeed not needed.

So - my mistake (sorry!), and thanks for your explanation.

(Needless to say that the PYTHONPATH with the hardcoded version and python 3.9 path was just for testing that at least that version would succeed.)

.

However, I'm still a bit surprised that `--import-mode=append` (which worked for python-zstandard) would cause problems for other packages. It ensures that `.` becomes the last item in sys.path so that `$BUILDROOT/usr/lib*/python3.*/site-packages` and all the `/usr/lib*/python3*` paths get prefered over an in-tree directory with the same name. IMHO this is exactly what you want (to test the installed modules) - otherwise you wouldn't set PYTHONPATH the way you do and do in-tree testing instead ;-)

```
# NOTE: all default paths shortened and merged to '/usr/lib/python38...' for readability
cb@tux:/dev/shm> PYTHONPATH=/foo pytest test-example.py
[...]
>       raise Exception(sys.path)
E       Exception: ['/dev/shm', '/usr/bin', '/foo', '/usr/lib/python38...']
[...]
cb@tux:/dev/shm> PYTHONPATH=/foo pytest --import-mode=append test-
example.py
[...]
>       raise Exception(sys.path)
E       Exception: ['/usr/bin', '/foo', '/usr/lib/python38...', '/dev/shm']
```

Of course moving away conflicting in-tree directories is also a valid workaround, but I'd still be interested how `--import-mode=append` can break something.

**Comment by bnavigator** [comment]
I must admit, I still do not fully understand the pytest and python interpreting import mechanics. Very often when I package a platform dependend package with `%pytest_arch` calls, the `--import-mode=append` approach fails. So I would recommend against hardcoding anything into the macro but append the correct flag on a package per package basis.

**Comment by cboltz** [comment]
That sounds interesting[tm] - and I like interesting problems.

Do you remember a few packages that break with `--import-mode=append`? I can't promise anything, but I'd be interested in looking at them, and maybe I can even help to find out what's going on.

BTW: I already tried cheroot - it needs the pushd/popd workaround with and without `--import-mode=append`

**Comment by s-t-e-v-e-n-k** [comment]
pytest's import code is ... wild, to say the least. The default is prepend, but [the pytest docs](https://docs.pytest.org/en/7.1.x/explanation/pythonpath.html) do a much better job of describing the drawbacks with each aspect.

**Comment by mcepl** [comment]
Also, let me add that there is a magical environment variable `PYTEST_ADDOPTS` which can be set before any callings of `%pytest` macro, and it will add options to the pytest run. E.g., you can add something like:

```sh
export PYTEST_ADDOPTS="--import-mode=importlib"
```

before your `%pytest` call.

**Comment by bnavigator** [comment]
See also discussion in #125
