### ISSUE TITLE
Missing {} around parameter in _python_sysconfig_path/var macros

### ISSUE THREAD

**Issue by StefanBruens** [openSUSE/python-rpm-macros#130]
https://github.com/openSUSE/python-rpm-macros/blob/1ed005549efea407ec176b4089641b499090b72e/macros/010-common-defs#L5-L7

Currently, the macro reports
```
[   62s] warning: line 47: Possible unexpanded macro in: PreReq: python = !!_%1_not_installed_!!
[   62s] error: line 47: Illegal char '!' (0x21) in: PreReq: python = !!_%1_not_installed_!!
```

in case the wanted python is not installed, instead of the apparently wanted e.g. "!!_python3_not_installed_!!".

This should apparently read `echo "!!_%{1}_not_installed_!!"`.

**Comment by bnavigator** [comment]
Good catch
