### ISSUE TITLE
Old "py_requires" macro for python2 fails to expand properly on Leap 15.4

### ISSUE THREAD

**Issue by StefanBruens** [openSUSE/python-rpm-macros#131]
```
%py_requires(d) \
BuildRequires: /usr/bin/python %{-d:python-devel} \
PreReq: python = %{py_ver}
```

The macro `py_requires` (from the python-base-2.7 package) should expand to `PreReq: python = 2.7`. Unfortunately, on Leap 15.4 the default flavor is 3.6, and the macro will fail in two different ways:

1. When python3-base is also installed, it will be expanded to `PreReq: python = 3.6`
2. Otherwise, the expansion of %{py_ver} will check for the python3 interpreter, and report an error:
`warning: line 47: Possible unexpanded macro in: PreReq: python = !!_%1_not_installed_!!`

For the second case, also see #130.

**Comment by bnavigator** [comment]
> 1. When python3-base is also installed, it will be expanded to `PreReq: python = 3.6`
> [because] the expansion of %{py_ver} will check for the python3 interpreter.

I agree, this is undesired behavior. The corresponding line here should be adjusted or removed: https://github.com/openSUSE/python-rpm-macros/blob/1ed005549efea407ec176b4089641b499090b72e/macros/010-common-defs#L48

(But someone will then have to fight to get an update of python-rpm-macros into Leap 15.4)

**Comment by bnavigator** [comment]
So I found out that %py_ver is overriden on tumbleweed by /usr/lib/rpm/suse/macros:
```
%py_ver     %(python -c "import sys; v=sys.version_info[:2]; print '%%d.%%d'%%v" 2>/dev/null || echo PYTHON-NOT-FOUND)
```

Which is not the case for 15.4.
