### ISSUE TITLE
libalternatives handling wrong

### ISSUE THREAD

**Issue by AdamMajer** [openSUSE/python-rpm-macros#133]
While looking at,

```
# rpm -V python310-chardet
.M.......  g /usr/share/libalternatives/chardetect
.M.......  g /usr/share/libalternatives/chardetect/1310.conf
```

and then at scripts

```
# rpm -q --scripts python310-chardet
preinstall scriptlet (using /bin/sh):
# If libalternatives is used: Removing old update-alternatives entries.


if [ "$1" -gt 0 ] && [ -f /usr/sbin/update-alternatives ]; then 
    update-alternatives --quiet --remove "chardetect" "/usr/bin/chardetect-3.10" 
fi
postinstall scriptlet (using /bin/sh):

 
mkdir -p /usr/share/libalternatives/chardetect
echo binary=/usr/bin/chardetect-3.10 >/usr/share/libalternatives/chardetect/1310.conf
echo group=chardetect >>/usr/share/libalternatives/chardetect/1310.conf
postuninstall scriptlet (using /bin/sh):

: # no uninstall action for libalternatives
```

The most obvious problems here are:

1. these is not suppose to be ghost files
2. the files are to be installed, not generated by script

So if these are to be generated by some macro, it must be part of the %build or %install.

**Comment by bnavigator** [comment]
---> @schubi2

**Comment by bnavigator** [comment]
I wouldnt't call it "wrong". In fact in rpmlint it is specifically okayed:

https://github.com/rpm-softwaremanagement/rpmlint/blob/af399ec51490836aebfbbe1fd5a0bc9ec8fcc1bd/rpmlint/descriptions/AlternativesCheck.toml#L41

But I agree that installing it in `%install` is better: #135
