### ISSUE TITLE
Cannot add `--install-options` to %pyproject_install

### ISSUE THREAD

**Issue by dcermak** [openSUSE/python-rpm-macros#147]
I would like to use `%pyproject_install` with the flag `--install-option=` to pass `--install-script %{_prefix}/lib/obs/service` to the installer directly, but the current scriptlet doesn't support this:
```ShellSession
278af5c37135:/ # rpm -E "%{pyproject_wheel --install-option='--install-data %{_prefix}/lib/obs/service'}"
pyproject_wheel: invalid option -- '''
error: Unknown option ' in pyproject_wheel(+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-=)
```

**Comment by bnavigator** [comment]
A limitation of the Lua macro.

Passing arguments with whitespace through a chain of parsers (rpm, lua, bash, ...) is hard and destined to fail.

Did you try using `PIP_INSTALL_SCRIPT`? https://pip.pypa.io/en/stable/topics/configuration/#environment-variables

**Comment by bnavigator** [comment]
Oh, and one more alternative is to not use whitespace but `=`:

```bash
> rpm -E '%python310_pyproject_wheel --install-options=---XXX=YYY'


last_flavor=`[ -f _current_flavor ] && cat _current_flavor || true` 
if [ -z "$last_flavor" ]; then last_flavor="tmp"; fi 
if [ "$last_flavor" != "python310" ]; then 
    if [ -d build ]; then mv build _build.$last_flavor; fi 
    if [ -d _build.python310 ]; then mv _build.python310 build; fi 
fi 
echo python310 > _current_flavor 
python_flavor=python310 
 
myargs="--install-options=---XXX=YYY" 
if [ -f ./dist/*-none-any.whl ]; then 
  echo "Already found a compatible wheel in ./dist" 
  mkdir -p ./build 
  cp ./dist/*-none-any.whl ./build/ 
else 
  /usr/bin/python3.10 -mpip wheel \
  --verbose --progress-bar off --disable-pip-version-check \
   \
  --use-pep517 --no-build-isolation \
  --no-deps \
  --wheel-dir ./build ${myargs:-.}
  if [ -f ./build/*-none-any.whl ]; then 
    mkdir -p ./dist 
    cp ./build/*-none-any.whl ./dist/ 
  fi 
fi

```

**Comment by dcermak** [comment]
Ben Greiner ***@***.***> writes:

> Oh, and one more alternative is to not use whitespace but `=`:
>
> ```bash
>> rpm -E '%python310_pyproject_wheel --install-options=---XXX=YYY'
>

This unfortunately doesn't work if `YYY` is a path or contains an rpm
macro :-(

> Did you try using `PIP_INSTALL_SCRIPT`? https://pip.pypa.io/en/stable/topics/configuration/#environment-variables

Yes and pip complained that I cannot override this setting and should
use --root instead (which we already set).

I'll have to fix the paths manually instead.


Thanks a lot for all these tricks!
