### ISSUE TITLE
Add python312 in <flavor>

### ISSUE THREAD

**Issue by clin1234** [openSUSE/python-rpm-macros#148]
I'm looking into building python312 and its subpackages on OBS, and it would be great to be able to build all available Python-related libraries already targeted for 3.10 and 3.11 for 3.12 on OpenSUSE.

**Comment by bnavigator** [comment]
[sr#1036434](https://build.opensuse.org/request/show/1036434)

**Comment by clin1234** [comment]
Thanks!
