### ISSUE TITLE
python_compileall fails to strip the buildroot

### ISSUE THREAD

**Issue by StefanBruens** [openSUSE/python-rpm-macros#150]
As can be seen here https://build.opensuse.org/build/science/openSUSE_Tumbleweed/x86_64/lal/_log :

```
[  700s] /usr/lib64/python3.9/site-packages/lal/__pycache__/__init__.cpython-39.opt-1.pyc differs at offset '575' (data)
[  700s] --- old /usr/lib64/python3.9/site-packages/lal/__pycache__/__init__.cpython-39.opt-1.pyc (hex)
[  700s] +++ new /usr/lib64/python3.9/site-packages/lal/__pycache__/__init__.cpython-39.opt-1.pyc (hex)
[  700s] @@ -1,7 +1,7 @@
[  700s]  00000200  02 2e 30 5a 02 63 64 a9  00 72 09 00 00 00 fa 68  |..0Z.cd..r.....h|
[  700s]  00000210  2f 68 6f 6d 65 2f 61 62  75 69 6c 64 2f 72 70 6d  |/home/abuild/rpm|
[  700s]  00000220  62 75 69 6c 64 2f 42 55  49 4c 44 52 4f 4f 54 2f  |build/BUILDROOT/|
[  700s] -00000230  6c 61 6c 2d 37 2e 32 2e  34 2d 32 34 2e 34 30 2e  |lal-7.2.4-24.40.|
[  700s] +00000230  6c 61 6c 2d 37 2e 32 2e  34 2d 32 34 2e 34 31 2e  |lal-7.2.4-24.41.|
[  700s]  00000240  78 38 36 5f 36 34 2f 75  73 72 2f 6c 69 62 36 34  |x86_64/usr/lib64|
[  700s]  00000250  2f 70 79 74 68 6f 6e 33  2e 39 2f 73 69 74 65 2d  |/python3.9/site-|
[  700s]  00000260  70 61 63 6b 61 67 65 73  2f 6c 61 6c 2f 5f 5f 69  |packages/lal/__i|
```

The whole extent can be seen by running  
`find /usr/lib64/python3.10/ -iname \*pyc -type f  -exec grep 'home/abuild' '{}' \; -ls`

1. This makes the cached files ineffective
2. It makes builds unreproducible

This can be trivially fixed by stripping the buildroot prefix:
https://docs.python.org/3/library/compileall.html#cmdoption-compileall-s

**Comment by StefanBruens** [comment]
@bmwiedemann

**Comment by StefanBruens** [comment]
Btw, why are **all** cache files deleted first? The filehash should be sufficient to detect a necessary recompile after editing.

 https://github.com/openSUSE/python-rpm-macros/blob/868757846f707ffcf351720b9e4efb3eb7fd743f/macros/010-common-defs#L178

**Comment by bmwiedemann** [comment]
> Btw, why are all cache files deleted first?

There are/were issues with python's `compile_all` that made the `.pyc` output depend on the order of input `.py` files and because python is one of the few languages where [globs are not sorted](http://bugs.python.org/issue30461), this happens quite a lot .

https://bugs.python.org/issue34033 is related.

And if we could call python there with `setarch -R $python` to disable ASLR as source of non-determinism that would also help.

CC @mcepl

**Comment by StefanBruens** [comment]
So apparently we should call py_compile with a single input file, each done with a separate process called from e.g `find -exec ...`.

**Comment by bnavigator** [comment]
> 2\. It makes builds unreproducible

Does it really? A different BUILDROOT means a different package revision.

> This can be trivially fixed by stripping the buildroot prefix: https://docs.python.org/3/library/compileall.html#cmdoption-compileall-s

Only for Python >= 3.9

**Comment by StefanBruens** [comment]
> > 2. It makes builds unreproducible
> 
> Does it really? A different BUILDROOT means a different package revision.

Yes. A different BUILDROOT can be caused by a changed rebuild counter.

**Comment by bmwiedemann** [comment]
`find` also processes files in non-deterministic filesystem-oder, so more like `find | sort | xargs -l`

While the core reproducible builds assume all inputs stay the same, rebuild counters matter in OBS where we want to avoid publishing a new build if nothing really changed. That saves bandwidth of mirrors and users and saves build power via build-tree-pruning (because you don't have to rebuild dependent packages of stuff that did not really change).

**Comment by StefanBruens** [comment]
> `find` also processes files in non-deterministic filesystem-readdir-order, so more like `find | sort | xargs -l`

As long as each input file is processed by a single python process, ordering does not matter. The non-determinism (at least some of it) comes from multiple files processed by a single python process.

**Comment by bnavigator** [comment]
> rebuild counters matter in OBS where we want to avoid publishing a new build if nothing really changed. 

But that does currently not happen even with the buildroot being present in the .pyc files, does it? Is there some filter for it in OBS?

**Comment by bnavigator** [comment]
#151 should implement what you suggested. See https://build.opensuse.org/project/show/home:bnavigator:python-rpm-macros for a project using it.

@StefanBruens can you confirm that this resolves the issue?

**Comment by StefanBruens** [comment]
Why not something like
 `python3 -c 'import py_compile; py_compile.compile("%{buildroot}/${file}", dfile="${file}")`

With your solution, the pyc no longer contains the buildroot, but has `./usr/lib/python...` instead, which seems awkward.

**Comment by bnavigator** [comment]
I don't see why your command should make any difference. Both variants depend on how the filename is passed.

**Comment by StefanBruens** [comment]
Why don´t you read the py_compile docs? https://docs.python.org/3.8/library/py_compile.html

The dfile argument is the source file name which is set in the pyc file. I.e. it achieves exact the same as the compileall `-s` parameter, but is available even with Python 3.5.

**Comment by StefanBruens** [comment]
```
pushd %{buildroot}
for file in `find usr/ -iname \*.py` ; do
    python3 -c 'import py_compile; py_compile.compile("%{buildroot}/${file}", dfile="/${file}")
done
```

**Comment by bnavigator** [comment]
Apart from the obvious syntax errors in your snippet this would compile all site-packages from all flavors with the primary python3. :clown_face:

**Comment by StefanBruens** [comment]
> Apart from the obvious syntax errors in your snippet this would compile all site-packages from all flavors with the primary python3. clown_face

Then just change `find usr/` to something flavor specific. Do the same for the interpreter. I said "something like" ... 

>  :clown_face: 

You enjoy being rude, don't you?
