### ISSUE TITLE
Conditionally switch off providing python3-* packages for primary set

### ISSUE THREAD

**Issue by mcepl** [openSUSE/python-rpm-macros#152]
Python36 packages in SLE-15 are actually providing python3-* packages, so if we switch off whole primary_interpreter business, we won't have conflicts between Python Stack packages and base SLE-15 ones.

The best would be the ability to switch it off on the project configuration level.

**Comment by mcepl** [comment]
Cc: @danigm @bnavigator @s-t-e-v-e-n-k

**Comment by mcepl** [comment]
@s-t-e-v-e-n-k any thoughts while we are sleeping? ;)

**Comment by s-t-e-v-e-n-k** [comment]
How does that help? If a customer has SLE-15 but not the module, we want to have python3-<foo> provided by SLE-15. But if they have the module enabled, we want that turned off, which appears to be a conflicting goal?

**Comment by bnavigator** [comment]
Whether a package provides extra python3-foo capability is not determined by `primary_python` but by the symlink target of /usr/bin/python3.

https://github.com/openSUSE/python-rpm-macros/blob/e704796c8d93949837cf24491800281a4f5611eb/flavor.in#L18-L26

https://github.com/openSUSE/python-rpm-macros/blob/e704796c8d93949837cf24491800281a4f5611eb/macros.lua#L190-L196

You could override it with redefining `%python36_provides` on your project config. But:

- If you provide files for python3.6/site-packages from two differently named packages python36-foo and python3-foo, there will be file conflicts. Not providing python3-foo capability in a python36-foo package will not help here.

- If you are "providing" python3-foo when you are actually not, there is something wrong in the project setup. Don't redefine `primary_interpreter` into something which is not primary on SLE-15. primary python must always be python 3.6 on 15.X.
https://build.opensuse.org/project/show/devel:languages:python:backports#comment-1733140

**Comment by mcepl** [comment]
> How does that help? If a customer has SLE-15 but not the module, we want to have python3- provided by SLE-15. But if they have the module enabled, we want that turned off, which appears to be a conflicting goal?

Do you take into consideration that generated binary packages for the standard SLE-15 are called python3-foo and NOT python36-foo?

**Comment by bnavigator** [comment]
> Do you take into consideration that generated binary packages for the standard SLE-15 are called python3-foo and NOT python36-foo?

What difference does it make? They could be called awesomefoo and still have provides `Provides: python3-foo`. The fixed convention in 15.x, including SLE-15, is that `python3` always means python 3.6. You should not mess around with that by redefining primary_python or primary_interpreter for special projects.

**Comment by mcepl** [comment]
> What difference does it make? They could be called awesomefoo and still have provides `Provides: python3-foo`. The fixed convention in 15.x, including SLE-15, is that `python3` always means python 3.6. You should not mess around with that by redefining primary_python or primary_interpreter for special projects.

I am not arguing with you. Thank you for the explanation how the stuff works, and yes redefinition of `%python36_provides` in the project config seems like the best idea so far.

**Comment by bnavigator** [comment]
So where do you have a `python36` flavor for 15.X? Is that the reason why there recently appeared some packages in Factory with a `%define skip_python36 1` although we removed that flavor from Tumbleweed a long time ago? I usually remove those lines because they makee no sense anymore.

If you are introducing such a thing to public or non-public 15.X projects and make changes in Factory packages for it you should definitely document it.

**Comment by dirkmueller** [comment]
@bnavigator yes, this is related. It is documented here as well as in the changes entry that came with those.

**Comment by mcepl** [comment]
> So where do you have a `python36` flavor for 15.X? Is that the reason why there recently appeared some packages in Factory with a `%define skip_python36 1` although we removed that flavor from Tumbleweed a long time ago? I usually remove those lines because they make no sense anymore.

We are talking about adding some “modern” (i.e., >3.6) Python packages to SLE-15 (completely not an official announcement, we are talking just about possibility studies, I am not talking in name of SUSE, etc.). You can observe those packages in Leap 15.

**Comment by bnavigator** [comment]
> We are talking about adding some “modern” (i.e., >3.6) Python packages to SLE-15 

That doesn't explain the existence of a `python36` flavor instead of the standard `python3` flavor which is Python 3.6 on 15.X. Nor does it explain your request that `python36` should not provide `python3`.

An additional python310 (or python39 or python311) flavor for SLE-15 should not interfere with any `python3` flavor or any otherwise named flavor providing `python3-foo`.

**Comment by bnavigator** [comment]
@dirkmueller: [sr#1064169 for flit-core](https://build.opensuse.org/request/show/1064169) declined.

Please come up with a concept of properly define macros instead of invaladint `%skip_python3` and introducing `%skip_python3?` for non-existing flavors. How would a future maintainer of the spec-file know what it is supposed to do?

**Comment by bnavigator** [comment]
@antlarr any comments? Your [sr#1061578](https://build.opensuse.org/request/show/1061578) seems related.

**Comment by bnavigator** [comment]
`%python36_provides %{nil}` only has an effect if you have a python36 in %pythons.  https://build.opensuse.org/projects/home:dirkmueller:acdc/prjconf does not.

**Comment by danigm** [comment]
If I understand the situation correctly, after reading all the comments again, we can conclude that there's no need "switch off providing python3-*".

The provides `python3-*` will only be created if `/usr/bin/python3` points to the flavor that's being build, and, as far as I know, that will be always correct.

So we can close this issue if there's no other related thing to discuss.

**Comment by mcepl** [comment]
I agree.
