### ISSUE TITLE
rewrite shebangs for "pythons python3" packages

### ISSUE THREAD

**Issue by dirkmueller** [openSUSE/python-rpm-macros#153]
For packages that build only one flavor (e.g. the primary_python / python3 flavor), currently nothing is rewriting the shebangs of installed scripts in %_bindir/ away from `/usr/bin/env python3` or `/usr/bin/python3` to the actual python interpreter. this is currently only done in `%python_clone`: 

```
        print(rpm.expand(string.format("sed -ri '1s@#!.*python.*@#!%s@' %s\\n", "%__" .. python, path)))\
```

we should split this out into a separate function that can be invoked either explicitly or implicitly (not sure whats better) at the end of `%install`.

**Comment by bnavigator** [comment]
Closed in #155
