### ISSUE TITLE
fdupes could be run for %doc files

### ISSUE THREAD

**Issue by mcepl** [openSUSE/python-rpm-macros#166]
```
[   20s] python-blinker-doc.noarch: W: files-duplicate /usr/share/doc/packages/python-blinker-doc/html/_static/blinker-named.png /usr/share/doc/packages/python-blinker-doc/html/_images/blinker-named.png
[   20s] Your package contains duplicated files that are not hard- or symlinks. You
[   20s] should use the %fdupes macro to link the files to one.
```

These are files which were never installed in `%install` section, but automagically via `%doc` as in

```spec
%files -n python-blinker-doc
%doc docs/_build/html
```

Also note, that this is a subpackage so the location is NOT in `/usr/share/doc/packages/%{name}` of the main package.

Now the question is whether we should make `fdupes` automatic dependency of all Python packages and run it automatically for any (sub-)packages containing any files in `%doc` (i.e., all packages).

**Comment by bnavigator** [comment]
`%doc` is evaluated from the `%files`  section in a different rpmbuild stage than we (python-rpm-macros) could inject an `%fdupes` call.

**Comment by mcepl** [comment]
Oh well, I liked the idea.
