### ISSUE TITLE
Create `%pytest` and `%pyunittest` variants per flavor

### ISSUE THREAD

**Issue by danigm** [openSUSE/python-rpm-macros#170]
For packages that doesn't use `%python_subpackages` there's no way to run the tests using the macros, just for the primary python without modifying the `%pythons` in the spec.

It could be great to be able to run tests with something like `%python3_pytest` and `%python3_pyunittest`.

**Comment by uncomfyhalomacro** [comment]
oh so this is why my qtile builds are failing.. and the wiki is outdated.

**Comment by mcepl** [comment]
> oh so this is why my qtile builds are failing.. and the wiki is outdated.

file a bug, please
