### ISSUE TITLE
the current %python3_fix_shebang_path eliminates any cmdline arguments in the shebang line

### ISSUE THREAD

**Issue by darix** [openSUSE/python-rpm-macros#175]
not sure how common that is in the python world.

A potential fix might be:

```
[ -f "$f" ] && sed -i -e "1s@#\\!.*python\S*@#\\!$(realpath %__python3)@" $f \
```

**Comment by bnavigator** [comment]
Are you sure? `\S*` only selects and replaces non-space characters. Every argument after the first space should be retained.

**Comment by bnavigator** [comment]
Not that common, but PR welcome.
