### ISSUE TITLE
python3 only is broken

### ISSUE THREAD

**Issue by wagner-certat** [openSUSE/python-rpm-macros#2]
The [docs](https://en.opensuse.org/openSUSE:Packaging_Python_Singlespec#Packages_for_single_Python_version) say that this:

    %undefine have_python2

results in no python2 packages. It doesn't build, but the files are added nevertheless:

    File not found: /home/abuild/rpmbuild/BUILDROOT/mypy-0.510-0.x86_64/usr/lib/python2.7/site-packages/*

**Comment by matejcik** [comment]
This now works completely differently. Instead of `%undefine have_python2`, you'll need to `%define skip_python2`.

I'll close the issue when the fixed prjconf hits Factory

**Comment by DimStar77** [comment]
"the fixed prjconf" - ? Maybe somebody wants to talk to me about the requested change?!

**Comment by matejcik** [comment]
I actually intended to talk to Ludwig about it. I did post on packaging ML, and when I left that comment, the "fixed prjconf" was only a prototype, so requesting a change would be premature.

**Comment by matejcik** [comment]
this is now in Factory

**Comment by termim** [comment]
Documentation should also be fixed ...

**Comment by sebix** [comment]
And the announcement on the mailing list
