### ISSUE TITLE
python to python-singlespec migration causes file conflicts

### ISSUE THREAD

**Issue by scarabeusiv** [openSUSE/python-rpm-macros#24]
In a case we happen to have binary in _bindir we get a conflict later on:

found conflict of python-xmldiff-0.6.10-13.14.x86_64 with python3-xmldiff-2.3-199.1.noarch:
  - /usr/bin/xmldiff

This can be handled per package by all the variants adding:
Conflicts: %{oldpython}-whatever < %{version}-%{release}

Question is wether we should do it in macros or have it done individualy per package.

**Comment by mcepl** [comment]
Yes, we have `update-alternatives` for that.
