### ISSUE TITLE
build loop does not execute additional commands

### ISSUE THREAD

**Issue by rjschwei** [openSUSE/python-rpm-macros#25]
The way %install and %build are replaced to loop for building with Python 2 and Python 3 does not execute additional commands.

For example:

%install
%python_install
mkdir -p %{buildroot}%{python_sitelib}/foo

will result in mkdir being executed only once. Since Python 2 gets built first "foo" then happens to be in python2_sitelib.

**Comment by jayvdb** [comment]
You can use the following to do a separate loop after the installs are completed.

```
%python_install
%python_expand mkdir -p %{buildroot}%{$python_sitelib}/foo
```

**Comment by scarabeusiv** [comment]
Yeah as John said.

The build loop is supposed to be used only for the operations it is handling, for the rest you need to use %python_expand macros.

As such this is not a bug but rather everything works as designed.
