### ISSUE TITLE
%pytest is emitting Python 2 bytecode into Python 3 site-packages

### ISSUE THREAD

**Issue by jayvdb** [openSUSE/python-rpm-macros#26]
I am told at https://build.opensuse.org/request/show/691930 that I should create an issue.

There are a few isolated cases where pytest puts Python 2 bytecode into the Python 3 site-packages, and the opposite also occurs.  pytest also deposits `foo.PYTEST` files into site-packages occasionally.

The problem is `pytest` itself, and the religious fervor of the use of the `%pytest` macro is just making this occur more often.

The only guaranteed way to make the macro not do this, would be `PYTHONDONTWRITEBYTECODE=1` etc, or by forcing pytest to not look in the buildroot (i.e. emulate `setup.py pytest`).

It should be ok to set `PYTHONDONTWRITEBYTECODE=1` as the existing bytecode should already exist, but there may be side-effects of not allowing pytest to create the `foo.PYTEST` files.  I couldnt find much info about those `foo.PYTEST` files.  I think a peek in pytest codebase is needed to understand them.

**Comment by mcepl** [comment]
I don't understand this. Looking at the [SPEC file with %pytest](https://build.opensuse.org/package/view_file/devel:languages:python/python-hyperframe/python-hyperframe.spec?expand=1), I can see that everything works just fine. My deep suspicion is that you have installed somewhere some old version of ``python-rpm-macros``, or python interpreter, or something. Please, retest, and if you can find some bug reproduceable on other machines, please, reopen with the additional information.

Thank you.

**Comment by jayvdb** [comment]
Oh my goodness. I keep telling you to read the logs, and you keep saying they pass without reading the logs.

**Comment by mcepl** [comment]
And I keep asking which logs. The ones I pointed out (which are without your suggested changes and thus they should fail), are passing.

**Comment by jayvdb** [comment]
I gave an excerpt of the log on https://build.opensuse.org/request/show/691930 . It was happening.   The excerpt actually shows it was happening.  If it has been fixed, the usual response is to give the commit that fixed it, or at least acknowledge the bug, not the 'deep suspicion' you have above.  I would give log links more but afaik OBS logs are not retained after a new build, which are very frequent.  Anyways, looking at the commits, I supposed https://github.com/openSUSE/python-rpm-macros/commit/c88be49b524927dc0ddd26e90cafbba43c8c1140 could have been the fix, if that 22 day old commit was only recently deployed.

I am now seeing similar problems in
```
Name        : python3-python-qpid-proton
Version     : 0.17.0
Release     : 8.3
Architecture: x86_64
Install Date: Mon 08 Apr 2019 08:23:15 AM WIB
Group       : Development/Libraries/Python
Size        : 2322692
License     : Apache-2.0
Signature   : RSA/SHA256, Sun 03 Feb 2019 05:01:06 AM WIB, Key ID b88b2fd43dbdc284
Source RPM  : qpid-proton-0.17.0-8.3.src.rpm
Build Date  : Sun 03 Feb 2019 05:00:15 AM WIB
Build Host  : cloud104
Relocations : (not relocatable)
Packager    : https://bugs.opensuse.org
Vendor      : openSUSE
URL         : http://qpid.apache.org/proton/
Summary     : Python language bindings for the Qpid Proton messaging framework
```
But I havent found the package .spec for that, to see why, or if it has been fixed.  I dont recall seeing the problem there last time I looked at the runtime package for it.

The PYTEST problem has been more frequently occurring, and I've checked again that it is happening at https://build.opensuse.org/build/devel:languages:python:numeric/openSUSE_Tumbleweed/x86_64/python-pandas/_log and https://build.opensuse.org/package/show/devel:languages:python:jupyter/python-jupyter_nbconvert ; the latter is using `%pytest` with `*PYTEST.pyc` files, and they are still there afaics.  Anyways, I'll dig further into those PYTEST to understand them better.  It seems far less problematic that the py2/py3 bytecode mixups which were happening.
