### ISSUE TITLE
.spec file names not handled in some cases

### ISSUE THREAD

**Issue by toabctl** [openSUSE/python-rpm-macros#3]
In OBS, .spec files can be named ```$package_container_name.spec.$repo_name```. That needs to be handled. Otherwise the error is:

error: line 30: Unknown tag: bad spec python-debtcollector.spec

**Comment by matejcik** [comment]
This should be fixed through 32550d01ee3a96c181c614c1d1bb3106be7b5ac9. Let's see how the rebuild goes.

**Comment by matejcik** [comment]
fixed
