### ISSUE TITLE
%pytest macro refuses to take argument with underscore

### ISSUE THREAD

**Issue by afaerber** [openSUSE/python-rpm-macros#32]
Test case: `%pytest --cov=colcon_core --cov-branch`

The macro appears to stumble over the underscore.
Locally overriding the macro to extend its argument expression (`...-_=`) resolves this.

Any reason this macro is so strict?

**Comment by scarabeusiv** [comment]
And why do you need to run coverage tests in OBS? Usually avoiding pytest-cov dependency is better solution.

But yea feel free to PR to include more characters there, we included those we thought that will be needed to be passed.

**Comment by afaerber** [comment]
> And why do you need to run coverage tests in OBS?

Because you complained about package submissions where tests were not run!!! In this case the usual py2pack-generated code was not working and I looked up what the upstream was running in Travis:

https://build.opensuse.org/package/show/home:a_faerber:ros/python-colcon-core

**Comment by scarabeusiv** [comment]
Yea travis includes even flake8 runs/etc that we can safely ommit. We just need sanity check that the basic of the package works even if we swap python internals, coverage for that is pointless, even if upstream does it.

**Comment by mcepl** [comment]
1. We need to run tests, not coverage, it doesn't matter for us at all. We won't be developing new unit tests after all.
2. Yes, `%pytest` macro doesn't take any double-scored options. The possible workaround is to set them in `$PYTEST_ADDOPTS` environmental variable. E:g.,
```
export PYTEST_ADDOPTS="--skip-fft"
```

**Comment by bnavigator** [comment]
> 2\. Yes, `%pytest` macro doesn't take any double-scored options. The possible workaround is to set them in `$PYTEST_ADDOPTS` environmental variable. E:g.,

Huh? That doesn't seem right to me. '--ignore breakingtestfile.py' and other parameters work just fine

**Comment by mcepl** [comment]
> Huh? That doesn't seem right to me. `--ignore breakingtestfile.py` and other parameters work just fine

Then I am sorry, you are even more awesome than I thought you were. It used to be a problem, but apparently it got fixed somewhere on the way.
