### ISSUE TITLE
%{py_ver} problems when only one flavour is enabled

### ISSUE THREAD

**Issue by jayvdb** [openSUSE/python-rpm-macros#34]
Like https://github.com/openSUSE/python-rpm-macros/issues/33 , I have a hacky conf which has py2 disabled - so only py3 is enabled.

The result is mostly good, but there are a few times when the macros are behaving oddly.

python-botocore.spec currently uses
```
%files %{python_files}
%doc README.rst
%license LICENSE.txt
%{python_sitelib}/botocore/
%{python_sitelib}/botocore-%{version}-py%{py_ver}.egg-info
```

Somehow the `%{py_ver}` is expanded to `PYTHON-NOT-FOUND`:

```console
[   64s] RPM build errors:
[   64s]     File not found: /home/abuild/rpmbuild/BUILDROOT/python-botocore-1.12.213-2.1.x86_64/usr/lib/python3.7/site-packages/botocore-1.12.213-pyPYTHON-NOT-FOUND.egg-info
[   64s] 
```

This also occurs at
https://build.opensuse.org/package/live_build_log/home:jayvdb:py3only/python-pytest-translations/openSUSE_Tumbleweed/x86_64

**Comment by jayvdb** [comment]
The easy workaround in `%files` is to use not use `%py_ver`, i.e. `%{python_sitelib}/foo-%{version}-py*.egg-info` .

But maybe the problem will still exist elsewhere, and might cause more subtle breakages/regressions.

**Comment by scarabeusiv** [comment]
actually py_ver is the deprecated thingy from rpm rather than from these macros and one should've used the properly expanded %python_version...

The bellow code will make it work:
```
Index: python-pytest-translations.spec
===================================================================
--- python-pytest-translations.spec     (revision f399b7fffad070c1c6c9888b51bd6a14)
+++ python-pytest-translations.spec     (working copy)
@@ -66,7 +66,7 @@
 %files %{python_files}
 %doc AUTHORS ChangeLog README.rst
 %license LICENSE
-%{python_sitelib}/pytest_translations-%{version}-py*.egg-info/
+%{python_sitelib}/pytest_translations-%{version}-py%{python_version}.egg-info/
 %{python_sitelib}/pytest_translations
```

**Comment by scarabeusiv** [comment]
It is even described in readme that you should use the full flavor names.

**Comment by jayvdb** [comment]
Sure, but we have a lot of packages currently using it.  I havent submitted change requests for those, as that is likely better done by a maintainer.

**Comment by scarabeusiv** [comment]
Yea, we will sed it out when we get to testing py3 only again (november/december). I got the py3 only system rolling year ago, but the showstopper is the mozilla javascript engine that is needed for policykit, without that we can't really generate py3 distribution so we gave up checking it for a while... You would not believe how many issues there were... :)
