### ISSUE TITLE
pypy3 bin suffixes

### ISSUE THREAD

**Issue by jayvdb** [openSUSE/python-rpm-macros#36]
I have a working pypy3 v7.1.1, and am now putting it through its paces and tidying up.

https://build.opensuse.org/package/show/home:jayvdb:pypy/pypy3
https://build.opensuse.org/project/prjconf/home:jayvdb:pypy

Currently the packages are busted as I am working on the purelib/platlib problem, but it was doing ok.  Previous set of working packages can be seen at

https://download.opensuse.org/repositories/home:/jayvdb:/pypy/openSUSE_Tumbleweed/noarch/

Besides the other "Python 3" only issues raised here recently, some of which effect pypy3 also (esp py_ver), the stand-out problem with pypy3 is that the "bin suffix" are sometimes `pp3.6` and othertimes `-3.6` , in the same build.  So for the nose package, I added `%{_bindir}/nosetests-3.6` to the `%files` as a hack to get it green.

I put "bin suffix" in quotes as I am not suggesting the bin_suffix macros have different values thoughout a single build - something else is likely at play.  Possibly the clone macro is not using the bin suffix macro, or something like that.

`-3.6` would definitely be wrong.  `pp3.6` is a bit odd, but it is as good a choice as any I suppose.

**Comment by scarabeusiv** [comment]
You should use %python_bin_suffix; that should take the pp and others into effect. Sadly many people were rather using %python_version which would cause issues like you describe or even worse use %{py_ver} which is really unreliable...

**Comment by jayvdb** [comment]
The problem I am describing is occurring with only the top level "clone" macros used - no direct use of `python_bin_suffix` , `python_version` or `py_ver`.

https://build.opensuse.org/package/rdiff/home:jayvdb:pypy/python-nose?opackage=python-nose&oproject=home%3Ajayvdb%3Apy3only&rev=4

(ignore the -xml bit; that will be fix in the next pypy3 rpms)

The only source of problems like you mention might be side effects of my hacky proj configs
https://build.opensuse.org/project/prjconf/home:jayvdb:py3only
https://build.opensuse.org/project/prjconf/home:jayvdb:pypy

Anyways, this is a low priority - If you dont see the problem immediately, I will dig into it a bit once pypy3 is submitted, and can probably fix this myself.

**Comment by mcepl** [comment]
What is the status of this issue? Working pypy3 would be awesome to have.

**Comment by mcepl** [comment]
No response, closing this. Please, feel free to reopen with the additional information.
