### ISSUE TITLE
Create macro for python compile with multiversion in mind.

### ISSUE THREAD

**Issue by scarabeusiv** [openSUSE/python-rpm-macros#41]
%if 0%{?have_python2} && ! 0%{?skip_python2}
%py_compile %{buildroot}%{python2_sitelib}/jaraco/
%py_compile -O %{buildroot}%{python2_sitelib}/jaraco/
%endif

%if 0%{?have_python3} && ! 0%{?skip_python3}
%py3_compile %{buildroot}%{python3_sitelib}/jaraco/
%py3_compile -O %{buildroot}%{python3_sitelib}/jaraco/
%endif

^ The above is way too hidious and we should create a wrapper that would do that with all pythons in mind.

**Comment by bnavigator** [comment]
#60 ?
