### ISSUE TITLE
[Help] How to test python package with only conftest.py?

### ISSUE THREAD

**Issue by kevinsmia1939** [openSUSE/python-rpm-macros#46]
Hello, 

I found a python package with a single test file called conftest.py under folder tests.
I add %pytest to the spec file but pytest does not see it, saying collected 0 items.
Does conftest.py must be test? How to make pytest see it?

https://build.opensuse.org/package/show/home:andythe_great/python-czifile

Thanks.

**Comment by bnavigator** [comment]
I that case we are just missing the actual test files in the PyPI package (there aren't any in the GitHub rep https://github.com/cgohlke/czifile either). `czifile/tests/conftest.py` does not contain any test, just a report hook. If the package really only defines conftest.py and puts the tests inside it (wich is not a good idea), just call `pytest conftest.py`

**Comment by kevinsmia1939** [comment]
> I that case we are just missing the actual test files in the PyPI package (there aren't any in the GitHub rep https://github.com/cgohlke/czifile either). `czifile/tests/conftest.py` does not contain any test, just a report hook. If the package really only defines conftest.py and puts the tests inside it (wich is not a good idea), just call `pytest conftest.py`

Thanks I will not test it then.
