### ISSUE TITLE
Handle %find_lang

### ISSUE THREAD

**Issue by matwey** [openSUSE/python-rpm-macros#5]
Hello,

I see the following warnings:

```
[   62s] python-djangorestframework.noarch: W: file-not-in-%lang /usr/lib/python2.7/site-packages/rest_framework/locale/ja/LC_MESSAGES/django.mo
[   62s] python-djangorestframework.noarch: W: file-not-in-%lang /usr/lib/python2.7/site-packages/rest_framework/locale/ko_KR/LC_MESSAGES/django.mo
[   62s] python-djangorestframework.noarch: W: file-not-in-%lang /usr/lib/python2.7/site-packages/rest_framework/locale/mk/LC_MESSAGES/django.mo
```

At the same time there is no way to handle this following https://en.opensuse.org/openSUSE:Packaging_Conventions_RPM_Macros#.25find_lang

 -f %{name}.lang leads to conflict between python{2,3}- packages

**Comment by tigerfoot** [comment]
With the release of Leap 42.3 and the continuous effort to singlespec d:l:p this would be a plus to have.

**Comment by toddrme2178** [comment]
Handling %lang_package would also be great.

**Comment by toddrme2178** [comment]
In the meantime, I have been doing something like this:

    %find_lang foo foo.lang
    %python_expand grep -F %{$python_sitelib} foo.lang > foo-%{$python_bin_suffix}.lang

This doesn't help with the `%files` section, though. I have had to make the individual `-lang` packages manually.

**Comment by tigerfoot** [comment]
@toddrme2178 did you have a example in dlp I'm stuck with colander
