### ISSUE TITLE
%pyunittest{,_arch} discover doesn't work

### ISSUE THREAD

**Issue by mcepl** [openSUSE/python-rpm-macros#57]
@s-t-e-v-e-n-k As the macro stands right now
```rpm
%pyunittest discover
```
generates (abbreviated) ``$python -munittest -v discover``, which is incorrect, because then unittest starts to search for ``-v`` module. The correct call is ``$python -munittest discover -v``. Macro should make sure that the ``-v`` argument is always in the last position of the generated code.

Hmm, that actually doesn’t work either, because then ``%pyunittest test`` lead to ``$python -munittest test -v`` and that is broken as well (it should be ``$python -munittest -v test``).

So, we have to probably actively search for ``discover`` keyword and modify our behaviour accordingly.

**Comment by s-t-e-v-e-n-k** [comment]
I think we should just drop -v for being awkward from the macro.
