### ISSUE TITLE
%python_uninstall_alternative not capable of manpages

### ISSUE THREAD

**Issue by sebix** [openSUSE/python-rpm-macros#6]
`%python_install_alternative` can handle manpages fine:
```
> rpmspec -E '%python_install_alternative pyblake2.1'
update-alternatives --install /usr/share/man/man1/pyblake2.1.gz pyblake2.1.gz /usr/share/man/man1/pyblake2-2.7.1.gz 27
```
But `%python_uninstall_alternative` can't:
```
> rpmspec -E '%python_uninstall_alternative pyblake2.1'
if [ ! -e "/usr/bin/pyblake2.1-2.7" ]; then 
    update-alternatives --quiet --remove "pyblake2.1" "/usr/bin/pyblake2.1-2.7" 
fi 
```
It refers to /usr/bin/

**Comment by matejcik** [comment]
that's true... OTOH, why are you installing a manpage alternative without the corresponding binary?

**Comment by sebix** [comment]
Because the package ships a manpage. I now do not ship it because I could not figure out how to do it right -.-

**Comment by matejcik** [comment]
you're supposed to group the manpage with the respective binary:
   
    %post
    %{python_install_alternative pyblake2 pyblake2.1}
    
    %postun
    %python_uninstall_alternative pyblake2

**Comment by sebix** [comment]
Could that be mentioned in the docs? Currently it creates the impression that it's possible to handle manpages with these macros.

**Comment by matejcik** [comment]
this is described both in the `%python_install_alternative` macro description, and [on the wiki](https://en.opensuse.org/openSUSE:Packaging_Python_Singlespec#Grouped_alternatives). Feel free to suggest how to make this clearer.

**Comment by sebix** [comment]
done
