### ISSUE TITLE
Provides: python3-foo for multiple python3 flavors

### ISSUE THREAD

**Issue by bnavigator** [openSUSE/python-rpm-macros#69]
Some dumb questions, I am sure you have thought about this but I don't see anything in the macros:

This may eventually build fully for Staging:N. But when it goes into the Tumbleweed repository, what will happen for users? Won't all python3-foo packages cease to exist? Don't we need the python3?-foo packages have a `Provides:` and `Obsoletes:`, for distribution updates to work? And as a result of that, will the python36-foo and python38-foo create numerous "have choice" unresolvables in the openSUSE Build System and yast/zypper?

_Originally posted by @bnavigator in https://github.com/openSUSE/python-rpm-macros/pull/65#issuecomment-713857543_

**Comment by scarabeusiv** [comment]
There will be primary interpreter (see the python38 for this) and all the pythonXY-bla will be provider of pythonX-bla.

**Comment by bnavigator** [comment]
We now see it in [Staging:N unresolvables](https://build.opensuse.org/project/monitor/openSUSE:Factory:Staging:N?arch_x86_64=1&defaults=0&repo_standard=1&unresolvable=1) e.g. python36-setuptools and python38-setuptools build but there is no provider for python3-setuptools
