### ISSUE TITLE
%python_subpackages and %python_files equivalent for packages 'foo' defining subpackage 'pythonXY-foo'

### ISSUE THREAD

**Issue by bnavigator** [openSUSE/python-rpm-macros#73]
We need a macro equivalent of the  `%python_subpackages` and `%python_files` pair for applications and libraries, which are not primarily python modules. Many such packages manually define a python2-foo and python3-foo but fail with multiple python3 flavors. e.g. [libpfm](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/libpfm)

Alternatively, the `%python_subpackages` macro could leave packages `foo` as is and only rewrite subpackage definitions marked accordingly. Right now it fails with https://github.com/openSUSE/python-rpm-macros/blob/31ccfc2dd315854d6c0f3953f02cfd3641a4eb7b/macros.lua#L205-L210 if used in a package not prefixed with python. Making everything multibuild as in [sr#844480](https://build.opensuse.org/request/show/844480) is not really feasible.

**Comment by mcepl** [comment]
Yes, just looking at [setools](https://build.opensuse.org/package/live_build_log/openSUSE:Factory:Staging:N/setools/standard/x86_64) and I am frankly not sure how to proceed. We obviously patch like:
```diff
--- setools.spec        (revision d2c5c1e3bf908f6f1ac8f7734af3768f)
+++ setools.spec        (working copy)
@@ -101,13 +101,13 @@
 
 %install
 %python_install
-%fdupes -s %{buildroot}%{python3_sitearch}
+%python_expand %fdupes %{buildroot}%{$python_sitearch}
 
 %files -n python3-setools
 %defattr(-,root,root,-)
-%dir %{python3_sitearch}/setools/
-%{python3_sitearch}/setools/*
-%{python3_sitearch}/setools*egg-info*
+%dir %{python_sitearch}/setools/
+%{python_sitearch}/setools/*
+%{python_sitearch}/setools*egg-info*
 
 %files console
 %defattr(-,root,root,-)
@@ -130,7 +130,7 @@
 
 %files gui
 %defattr(-,root,root,-)
-%{python3_sitearch}/setoolsgui*
+%{python_sitearch}/setoolsgui*
 %{_bindir}/apol
 %{_mandir}/man1/apol.1.gz
```
but this wouldn’t work, because `%{python_expand}` doesn’t.

**Comment by bnavigator** [comment]
Using semanage as example for packages that only need to provide a single flavor (apps):[sr#845831[(https://build.opensuse.org/request/show/845831)

It is a bit ugly, but it works.

If all the (python3) flavors actually should be provided, we need something else.

**Comment by mcepl** [comment]
No, we don’t need all python3 flavours, the primary one would be perfect, but `%%%{python3_primary_provider}` construct is something so ugly, I would love it to be hidden somehow. Couldn’t we somehow repurpose `%python3_build` etc.? So that these macros would know, that if `"%{python3_primary_provider}" != "python3"` and then they would behave accordingly?

**Comment by bnavigator** [comment]
After sleeping a night over it: It's actually quite simple: Just redefine `%pythons` or define skip_pythonXY for everything except the primary provider. Then `%python_expand` and all macros using it will do the right thing.

https://build.opensuse.org/request/show/845922

Because the flavorless macros are not expanded correctly in the `%files` section, you have to use the `python3_*` there, which expands to the default provider value as intended. :tada:
