### ISSUE TITLE
Handle .desktop and appdata.xml files

### ISSUE THREAD

**Issue by toddrme2178** [openSUSE/python-rpm-macros#8]
It would be nice if there was a way to handle .desktop and appdata.xml files. 

`%python_clone` could easily handle changing things like the executable and icon. However, there are things like the name and comment that probably would need to be changed as well, but there is no reliable automated way to do that, so a dedicated macro might be necessary.

**Comment by mcepl** [comment]
@toddrme2178 If you have any suggestions what exactly that macro should do, I am all ears. Otherwise, I will close this ticket in a week or so.
