### ISSUE TITLE
pkg build issue on OBS, while fine when built locally

### ISSUE THREAD

**Issue by frispete** [openSUSE/python-rpm-macros#92]
Hi Ben,

sorry for not being of any help with your ambitious multi flavor changes. I'm in the process of changing my primary job, and that limits my fun work significantly ATM.

Before start tackling projects with huge amounts of failing python packages, I decided to look at low hanging fruits, and here's (a good?) one: [ptex build](https://build.opensuse.org/package/live_build_log/home:frispete:blender/ptex/openSUSE_Tumbleweed/x86_64). Of course, I also tried to build against `devel:languages:python:Factory/python-rpm-macros`, but that didn't change the outcome. A local build is fine, while an OBS build fails with:

```
[   19s] + exec rpmbuild -ba --define '_srcdefattr (-,root,root)' --nosignature --define '_build_create_debug 1' --define 'disturl obs://build.opensuse.org/home:frispete:blender/openSUSE_Tumbleweed/e6bb4caa8d82415798a8b34c0ddb1357-ptex' /home/abuild/rpmbuild/SOURCES/ptex.spec
[   19s] setting SOURCE_DATE_EPOCH=1594252800
[   19s] error: Failed build dependencies:
[   19s] 	python36-packaging is needed by ptex-2.3.2-5.17.x86_64
```

Obviously, OBS fails to expand `%{python_module packaging}` correctly. In fact, not a single python36 package is pulled.

Do we really need to redefine `%python_module` in each and every prjconf somehow?

**Comment by bnavigator** [comment]
Hi Pete. 

Your project should actually pull in the prjconf from Factory. If it doesn't there might be a quirk in your setup. Did you try to change your meta from: `<path project="openSUSE:Tumbleweed" repository="standard"/>` to: `<path project="openSUSE:Factory" repository="standard"/>` ?

**Comment by DimStar77** [comment]
You fall victim of https://github.com/openSUSE/open-build-service/issues/4088

Please disable and then re-enable build of your project in OBS

**Comment by frispete** [comment]
Ahoy sailors, land in sight!

Again, you made my day, Dominique. :smile: Even my pathological `home:frispete:python` project is about to getting into a  state, where it's possible to work from. (I constantly try to beat me to it, Ben!)

As an aside, I can imagine, that creating an API call to trigger a deep project check can be challenging without creating a huge DoS surface.

While at it, last week, my local OBS (2.10.8)  started to behave naughtily. It produced remote errors for both uplink API's, `pmbs` and `openSUSE` (503 remote error, Service Unavailable). This week, I found a solution: `obs_admin --deep-check-project ...` recovered from this mess.

**Comment by mcepl** [comment]
So, what's the status of this issue? COuld I close it?

**Comment by mcepl** [comment]
No response, closing this. Please, feel free to reopen with the additional information.
