### ISSUE TITLE
%have_<flavor> is not produced for non primary python3 flavors.

### ISSUE THREAD

**Issue by bnavigator** [openSUSE/python-rpm-macros#96]
The README says:
> %have_\<flavor\>. Defined as 1 if the flavor is present in the build environment. Undefined otherwise.

But the specfiles for the python interpreters do this:
```spec
# RPM macros
%if %{primary_interpreter}
mkdir -p %{buildroot}%{_rpmconfigdir}/macros.d/
install -m 644 %{SOURCE7} %{buildroot}%{_rpmconfigdir}/macros.d/ # macros.python3
%endif
```

And macros.python3 only has
```
%have_python3   1
```

So we never get `%have_python38` and so on.

This needs to be fixed in the specfiles, as the these definitions are not from python-rpm-macros (unless ` 0%{?suse_version} < 1330` )

**Comment by mcepl** [comment]
Actually it doesn’t even have to be ``%{SOURCE7}``, here-string would be enough.

**Comment by bnavigator** [comment]
It doesn't matter how you produce macros.python3. My point is that we also need macros.python36 and macros.python39

**Comment by bnavigator** [comment]
Closed by https://build.opensuse.org/request/show/870493
